[package]
name = "instplot-studio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
in-place-update-preview = []

[build-dependencies]
ed25519-dalek.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.build-dependencies]
winresource = "=0.1.31"

[target.'cfg(windows)'.dependencies]
windows = { version = "=0.62.2", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_Com", "Win32_System_Registry", "Win32_System_Threading", "Win32_UI_Shell"] }

[dependencies]
atomicwrites.workspace = true
directories.workspace = true
ed25519-dalek.workspace = true
eframe.workspace = true
getrandom = "=0.3.4"
instplot-export.workspace = true
instplot-core.workspace = true
instplot-io.workspace = true
instplot-layout.workspace = true
serde.workspace = true
serde_json.workspace = true
semver.workspace = true
sha2.workspace = true
time.workspace = true
instplot-render.workspace = true
instplot-text.workspace = true
ttf-parser = "=0.25.1"
instplot-ui.workspace = true
percent-encoding.workspace = true
url.workspace = true
ureq.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
rfd = { workspace = true, features = ["xdg-portal"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation.workspace = true

[target.'cfg(not(target_os = "linux"))'.dependencies]
rfd.workspace = true
