[package]
name = "instplot-layout"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
parley = "=0.11.1"
instplot-render.workspace = true
instplot-text = { path = "../instplot-text" }
ttf-parser = "=0.25.1"

[dev-dependencies]
instplot-export.workspace = true
