#!/usr/bin/env python3
"""Run the evidence-based Part A audit and identify exact failures.

Exit codes:
  0  every check in the selected scope passed
  1  at least one check failed
  2  no failure, but required evidence/tool/manual review is incomplete
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import time
import tomllib
import urllib.error
import urllib.request
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "target" / "part-a-audit"
PROTOTYPES = (
    "studio-render-spike",
    "text-shaping-spike",
    "export-backend-spike",
    "plotine-comparison",
    "ui-shell-spike",
    "layout-engine-spike",
)
FONT_DIR = ROOT / "prototypes" / "text-shaping-spike" / "assets" / "fonts"
RISKY_LICENSES = re.compile(r"\b(?:AGPL|GPL|LGPL|SSPL|BUSL|CPAL|EUPL)(?:[-.0-9+]*)\b", re.I)
ALLOWED_LICENSES = {
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "MIT",
    "OFL-1.1",
    "Ubuntu-font-1.0",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
}
ALLOWED_EXCEPTIONS = {"LLVM-exception"}
ERROR_LINES = re.compile(
    r"(?:error(?:\[|:)|failed|failure|panicked|assertion|mismatch|missing|not found)",
    re.I,
)


@dataclass
class Check:
    check_id: str
    category: str
    requirement: str
    status: str
    summary: str
    details: list[str] = field(default_factory=list)
    command: list[str] | None = None
    cwd: str | None = None
    log: str | None = None
    evidence: list[str] = field(default_factory=list)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--profile",
        choices=("current", "windows"),
        default="current",
        help="audit the current host, or require a native Windows host",
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help="do not query crates.io; release-activity evidence becomes blocked",
    )
    parser.add_argument(
        "--manual-evidence",
        type=Path,
        help="completed manual-evidence JSON generated by a previous run",
    )
    parser.add_argument(
        "--automated-only",
        action="store_true",
        help="run the complete automated scope without claiming manual readiness",
    )
    parser.add_argument(
        "--skip-validation",
        action="store_true",
        help="reuse an existing validation summary (never treated as fresh evidence)",
    )
    return parser.parse_args()


def run(argv: list[str], cwd: Path) -> tuple[int, float, str]:
    started = time.monotonic()
    try:
        completed = subprocess.run(
            argv,
            cwd=cwd,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            errors="replace",
        )
        return completed.returncode, time.monotonic() - started, completed.stdout
    except OSError as error:
        return 127, time.monotonic() - started, f"{type(error).__name__}: {error}\n"


def run_separate(argv: list[str], cwd: Path) -> tuple[int, float, str, str]:
    started = time.monotonic()
    try:
        completed = subprocess.run(
            argv,
            cwd=cwd,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            errors="replace",
        )
        return (
            completed.returncode,
            time.monotonic() - started,
            completed.stdout,
            completed.stderr,
        )
    except OSError as error:
        return 127, time.monotonic() - started, "", f"{type(error).__name__}: {error}\n"


def relative(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path.resolve())


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def diagnostic_excerpt(output: str, limit: int = 20) -> list[str]:
    matches = [line.strip() for line in output.splitlines() if ERROR_LINES.search(line)]
    return matches[:limit] or output.splitlines()[-min(limit, len(output.splitlines())) :]


def license_has_allowed_path(expression: str) -> tuple[bool, set[str]]:
    """Evaluate whether an SPDX-like expression offers an approved license path."""

    normalized = re.sub(r"\s*/\s*", " OR ", expression)
    tokens = re.findall(r"\(|\)|AND|OR|WITH|[A-Za-z0-9.+-]+", normalized)
    position = 0
    unknown: set[str] = set()

    def atom() -> bool:
        nonlocal position
        if position >= len(tokens):
            raise ValueError("unexpected end of license expression")
        token = tokens[position]
        if token == "(":
            position += 1
            value = parse_or()
            if position >= len(tokens) or tokens[position] != ")":
                raise ValueError("unclosed parenthesis in license expression")
            position += 1
            return value
        position += 1
        if token not in ALLOWED_LICENSES and not RISKY_LICENSES.search(token):
            unknown.add(token)
        return token in ALLOWED_LICENSES

    def parse_with() -> bool:
        nonlocal position
        value = atom()
        if position < len(tokens) and tokens[position] == "WITH":
            position += 1
            if position >= len(tokens):
                raise ValueError("WITH is missing an exception")
            exception = tokens[position]
            position += 1
            if exception not in ALLOWED_EXCEPTIONS:
                unknown.add(exception)
            value = value and exception in ALLOWED_EXCEPTIONS
        return value

    def parse_and() -> bool:
        nonlocal position
        value = parse_with()
        while position < len(tokens) and tokens[position] == "AND":
            position += 1
            value = parse_with() and value
        return value

    def parse_or() -> bool:
        nonlocal position
        value = parse_and()
        while position < len(tokens) and tokens[position] == "OR":
            position += 1
            value = parse_and() or value
        return value

    result = parse_or()
    if position != len(tokens):
        raise ValueError(f"unexpected token {tokens[position]}")
    return result, unknown


def command_check(
    output_dir: Path,
    check_id: str,
    category: str,
    requirement: str,
    argv: list[str],
    cwd: Path = ROOT,
) -> Check:
    exit_code, duration, output = run(argv, cwd)
    log_path = output_dir / "logs" / f"{check_id}.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_path.write_text(output, encoding="utf-8")
    if exit_code == 0:
        return Check(
            check_id,
            category,
            requirement,
            "pass",
            f"command passed in {duration:.2f}s",
            command=argv,
            cwd=relative(cwd),
            log=relative(log_path),
        )
    return Check(
        check_id,
        category,
        requirement,
        "fail",
        f"command exited with {exit_code} after {duration:.2f}s",
        details=diagnostic_excerpt(output),
        command=argv,
        cwd=relative(cwd),
        log=relative(log_path),
    )


def check_platform(profile: str) -> Check:
    current = platform.system()
    if profile == "windows" and current != "Windows":
        return Check(
            "native-platform",
            "environment",
            "Windows evidence must be captured on native Windows, not Wine or another OS",
            "fail",
            f"--profile windows requested on {current}",
            details=["Run scripts/audit_part_a.ps1 from the target Windows machine."],
        )
    return Check(
        "native-platform",
        "environment",
        "record and enforce the native audit platform",
        "pass",
        f"native platform is {current}",
    )


def check_toolchain() -> Check:
    code, _, output = run(["rustc", "--version"], ROOT)
    expected = "rustc 1.98.0"
    if code != 0 or not output.startswith(expected):
        return Check(
            "pinned-toolchain",
            "environment",
            "use the repository-pinned Rust 1.98.0 toolchain",
            "fail",
            f"expected {expected}, observed {output.strip() or f'exit {code}'}",
        )
    clippy_code, _, clippy = run(["cargo", "clippy", "--version"], ROOT)
    if clippy_code != 0 or "0.1.98" not in clippy:
        return Check(
            "pinned-toolchain",
            "environment",
            "Rust 1.98.0 and its Clippy component are required",
            "fail",
            "Clippy for the pinned toolchain is unavailable or has the wrong version",
            details=[clippy.strip()],
        )
    return Check(
        "pinned-toolchain",
        "environment",
        "use Rust 1.98.0 with matching Clippy",
        "pass",
        f"{output.strip()}; {clippy.strip()}",
    )


def run_validation(output_dir: Path, skip: bool) -> Check:
    validation_dir = output_dir / "validation"
    summary_path = validation_dir / "summary.json"
    if skip:
        return Check(
            "part-a-validation",
            "implementation",
            "fresh format, test, Clippy, typography, export and visual validation",
            "blocked",
            "validation was explicitly skipped; cached results are not fresh evidence",
        )
    check = command_check(
        output_dir,
        "part-a-validation-command",
        "implementation",
        "run the complete six-prototype Part A validation",
        [sys.executable, "scripts/validate_part_a.py", "--output-dir", str(validation_dir)],
    )
    if not summary_path.is_file():
        check.check_id = "part-a-validation"
        check.status = "fail"
        check.summary = "validation did not produce summary.json"
        return check
    try:
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        check.check_id = "part-a-validation"
        check.status = "fail"
        check.summary = f"validation summary is unreadable: {error}"
        return check
    failed = summary.get("failed_checks", [])
    check.check_id = "part-a-validation"
    check.evidence = [relative(summary_path)]
    if check.status == "pass" and summary.get("result") == "pass" and summary.get("passed") == 21:
        check.summary = "all 21 local Part A checks passed"
        return check
    check.status = "fail"
    check.summary = f"validation failed: {summary.get('passed', 0)} passed, {summary.get('failed', '?')} failed"
    check.details = [f"failed check: {name}" for name in failed]
    for item in summary.get("checks", []):
        if item.get("result") != "fail":
            continue
        log_path = ROOT / item["log"]
        if log_path.is_file():
            check.details.extend(
                f"{item['name']}: {line}"
                for line in diagnostic_excerpt(log_path.read_text(encoding="utf-8", errors="replace"), 5)
            )
    return check


def check_font_assets() -> Check:
    sums_path = FONT_DIR / "SHA256SUMS"
    if not sums_path.is_file():
        return Check(
            "font-assets",
            "typography",
            "verify every bundled font and provenance asset by SHA-256",
            "fail",
            "SHA256SUMS is missing",
        )
    errors: list[str] = []
    evidence: list[str] = [relative(sums_path)]
    for line_number, line in enumerate(sums_path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        match = re.fullmatch(r"([0-9a-f]{64})  (.+)", line)
        if not match:
            errors.append(f"SHA256SUMS:{line_number}: malformed entry")
            continue
        expected, name = match.groups()
        path = FONT_DIR / name
        if not path.is_file():
            errors.append(f"missing asset: {relative(path)}")
            continue
        actual = sha256(path)
        evidence.append(f"{relative(path)} sha256={actual}")
        if actual != expected:
            errors.append(f"{name}: expected {expected}, got {actual}")
    required = {
        "TeXGyreHeros-Regular.otf",
        "TeXGyreHeros-Italic.otf",
        "TeXGyreHeros-Bold.otf",
        "TeXGyreHeros-BoldItalic.otf",
        "GUST-FONT-LICENSE.txt",
        "MANIFEST-TeX-Gyre-Heros.txt",
        "README-TeX-Gyre-Heros.txt",
    }
    listed = {
        line.split("  ", 1)[1]
        for line in sums_path.read_text(encoding="utf-8").splitlines()
        if "  " in line
    }
    errors.extend(f"required asset is not checksummed: {name}" for name in sorted(required - listed))
    return Check(
        "font-assets",
        "typography",
        "verify four OTF faces, license and provenance assets by SHA-256",
        "fail" if errors else "pass",
        "font asset integrity failed" if errors else "all required font assets match their pinned hashes",
        details=errors,
        evidence=evidence,
    )


def check_no_system_font_calls() -> Check:
    patterns = (
        "load_system_fonts",
        "load_system_font",
        "SystemSource::new",
        "Database::load_system_fonts",
    )
    matches: list[str] = []
    for path in sorted((ROOT / "prototypes").glob("**/*.rs")):
        if "target" in path.parts:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for line_number, line in enumerate(text.splitlines(), 1):
            if any(pattern in line for pattern in patterns):
                matches.append(f"{relative(path)}:{line_number}: {line.strip()}")
    return Check(
        "no-system-font-api",
        "typography",
        "publication code must not invoke system-font discovery APIs",
        "fail" if matches else "pass",
        "forbidden system-font API use found" if matches else "no forbidden system-font API calls found",
        details=matches,
    )


def load_metadata(
    output_dir: Path, offline: bool
) -> tuple[list[Check], dict[tuple[str, str, str], dict[str, Any]], bool]:
    checks: list[Check] = []
    packages: dict[tuple[str, str, str], dict[str, Any]] = {}
    for prototype in PROTOTYPES:
        manifest = ROOT / "prototypes" / prototype / "Cargo.toml"
        check_id = f"metadata-{prototype}"
        argv = [
                "cargo",
                "metadata",
                "--manifest-path",
                str(manifest),
                "--locked",
                "--format-version",
                "1",
            ]
        if offline:
            argv.insert(-2, "--offline")
        code, duration, stdout, stderr = run_separate(argv, ROOT)
        output = stderr + stdout
        log_path = output_dir / "logs" / f"{check_id}.log"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        log_path.write_text(output, encoding="utf-8")
        if code != 0:
            checks.append(
                Check(
                    check_id,
                    "dependencies",
                    f"resolve {prototype} from its lock file without network mutation",
                    "blocked" if offline and "failed to download" in output else "fail",
                    (
                        f"offline cache is incomplete after {duration:.2f}s"
                        if offline and "failed to download" in output
                        else f"cargo metadata failed after {duration:.2f}s"
                    ),
                    details=diagnostic_excerpt(output),
                    log=relative(log_path),
                )
            )
            continue
        try:
            metadata = json.loads(stdout)
        except json.JSONDecodeError as error:
            checks.append(
                Check(
                    check_id,
                    "dependencies",
                    f"parse {prototype} cargo metadata",
                    "fail",
                    f"cargo metadata returned invalid JSON: {error}",
                    details=diagnostic_excerpt(output),
                    log=relative(log_path),
                )
            )
            continue
        for package in metadata["packages"]:
            key = (package["name"], package["version"], package.get("source") or "path")
            packages[key] = package
        checks.append(
            Check(
                check_id,
                "dependencies",
                f"resolve {prototype} from Cargo.lock in {'offline ' if offline else ''}locked mode",
                "pass",
                f"resolved {len(metadata['packages'])} packages in {duration:.2f}s",
                log=relative(log_path),
            )
        )
    return checks, packages, all(check.status == "pass" for check in checks)


def audit_dependency_metadata(
    output_dir: Path,
    packages: dict[tuple[str, str, str], dict[str, Any]],
    complete: bool,
) -> list[Check]:
    inventory = []
    missing_license: list[str] = []
    incompatible_license: list[str] = []
    copyleft_alternatives: list[str] = []
    native_links: list[str] = []
    msrv_too_new: list[str] = []
    for key in sorted(packages):
        package = packages[key]
        item = {
            "name": package["name"],
            "version": package["version"],
            "source": package.get("source"),
            "license": package.get("license"),
            "license_file": package.get("license_file"),
            "rust_version": package.get("rust_version"),
            "links": package.get("links"),
            "manifest_path": package.get("manifest_path"),
        }
        inventory.append(item)
        if (package.get("source") or "").startswith("registry+"):
            expression = package.get("license")
            if not expression and not package.get("license_file"):
                missing_license.append(f"{package['name']} {package['version']}")
            elif expression:
                try:
                    allowed_path, unknown = license_has_allowed_path(expression)
                except ValueError as error:
                    incompatible_license.append(
                        f"{package['name']} {package['version']}: {expression} ({error})"
                    )
                else:
                    if not allowed_path or unknown:
                        incompatible_license.append(
                            f"{package['name']} {package['version']}: {expression}"
                            + (f" unknown={sorted(unknown)}" if unknown else "")
                        )
                    elif RISKY_LICENSES.search(expression):
                        copyleft_alternatives.append(
                            f"{package['name']} {package['version']}: {expression}"
                        )
        if package.get("links"):
            native_links.append(
                f"{package['name']} {package['version']}: links={package['links']}"
            )
        rust_version = package.get("rust_version")
        if rust_version and version_tuple(rust_version) > (1, 98, 0):
            msrv_too_new.append(f"{package['name']} {package['version']}: rust-version={rust_version}")
    inventory_path = output_dir / "dependency-inventory.json"
    write_json(inventory_path, inventory)
    if not complete:
        return [
            Check(
                check_id,
                category,
                requirement,
                "blocked",
                "dependency metadata is incomplete; no pass/fail conclusion is allowed",
                evidence=[relative(inventory_path)],
            )
            for check_id, category, requirement in (
                (
                    "dependency-license-metadata",
                    "licenses",
                    "audit declared licenses for the complete registry dependency graph",
                ),
                (
                    "dependency-msrv-metadata",
                    "msrv",
                    "audit declared MSRV for the complete dependency graph",
                ),
                (
                    "native-link-inventory",
                    "dependencies",
                    "inventory native link targets for the complete dependency graph",
                ),
            )
        ]
    license_errors = missing_license + incompatible_license
    return [
        Check(
            "dependency-license-metadata",
            "licenses",
            "every registry dependency declares metadata and offers an approved license path",
            "fail" if license_errors else "pass",
            "dependency license metadata requires action" if license_errors else "every registry dependency offers an approved permissive license path",
            details=[*(f"missing: {item}" for item in missing_license), *incompatible_license],
            evidence=[relative(inventory_path)],
        ),
        Check(
            "dependency-license-alternatives",
            "licenses",
            "report dependencies that offer both permissive and copyleft alternatives",
            "warning" if copyleft_alternatives else "pass",
            f"{len(copyleft_alternatives)} package version(s) require choosing the permissive alternative" if copyleft_alternatives else "no copyleft alternative appears in dependency license expressions",
            details=copyleft_alternatives,
            evidence=[relative(inventory_path)],
        ),
        Check(
            "dependency-msrv-metadata",
            "msrv",
            "declared dependency rust-version must not exceed Rust 1.98.0",
            "fail" if msrv_too_new else "pass",
            "dependency requires a newer Rust compiler" if msrv_too_new else "no declared dependency MSRV exceeds Rust 1.98.0; the full build also runs on 1.98.0",
            details=msrv_too_new,
            evidence=[relative(inventory_path)],
        ),
        Check(
            "native-link-inventory",
            "dependencies",
            "inventory crates declaring native link targets for platform review",
            "warning" if native_links else "pass",
            f"{len(native_links)} native link declaration(s) require platform awareness" if native_links else "no Cargo package declares a native links target",
            details=native_links,
            evidence=[relative(inventory_path)],
        ),
    ]


def version_tuple(value: str) -> tuple[int, int, int]:
    numbers = [int(part) for part in re.findall(r"\d+", value)[:3]]
    return tuple((numbers + [0, 0, 0])[:3])  # type: ignore[return-value]


def check_advisories(output_dir: Path) -> Check:
    version_code, _, version_output = run(["cargo", "audit", "--version"], ROOT)
    if version_code != 0:
        return Check(
            "rustsec-advisories",
            "security",
            "scan every Cargo.lock against the RustSec advisory database",
            "blocked",
            "cargo-audit is not installed",
            details=[
                "Install a reviewed cargo-audit version, then rerun this script.",
                version_output.strip(),
            ],
        )
    failures: list[str] = []
    evidence: list[str] = [version_output.strip()]
    combined_log = output_dir / "logs" / "rustsec-advisories.log"
    log_parts: list[str] = []
    for prototype in PROTOTYPES:
        lock = ROOT / "prototypes" / prototype / "Cargo.lock"
        code, _, output = run(["cargo", "audit", "--file", str(lock)], ROOT)
        log_parts.append(f"## {prototype}\n{output}")
        if code != 0:
            failures.append(prototype)
    combined_log.parent.mkdir(parents=True, exist_ok=True)
    combined_log.write_text("\n".join(log_parts), encoding="utf-8")
    evidence.append(relative(combined_log))
    return Check(
        "rustsec-advisories",
        "security",
        "scan every Cargo.lock against the RustSec advisory database",
        "fail" if failures else "pass",
        f"advisory scan failed for: {', '.join(failures)}" if failures else "all lock files passed cargo-audit",
        details=failures,
        evidence=evidence,
    )


def direct_registry_dependencies() -> set[str]:
    names: set[str] = set()
    for prototype in PROTOTYPES:
        manifest = ROOT / "prototypes" / prototype / "Cargo.toml"
        data = tomllib.loads(manifest.read_text(encoding="utf-8"))
        for section in ("dependencies", "dev-dependencies", "build-dependencies"):
            for name, value in data.get(section, {}).items():
                if isinstance(value, str) or (isinstance(value, dict) and "path" not in value):
                    names.add(name)
    return names


def check_release_activity(output_dir: Path, offline: bool) -> Check:
    dependencies = sorted(direct_registry_dependencies())
    report_path = output_dir / "release-activity.json"
    if offline:
        return Check(
            "release-activity",
            "maintenance",
            "record current crates.io release activity for direct registry dependencies",
            "blocked",
            "--offline prevents the time-sensitive crates.io query",
            details=dependencies,
        )
    results: list[dict[str, Any]] = []
    errors: list[str] = []
    for name in dependencies:
        request = urllib.request.Request(
            f"https://crates.io/api/v1/crates/{name}",
            headers={"User-Agent": "InstPlot-Studio-Part-A-Audit/1.0"},
        )
        try:
            with urllib.request.urlopen(request, timeout=20) as response:
                payload = json.load(response)
            crate = payload["crate"]
            results.append(
                {
                    "name": name,
                    "newest_version": crate.get("newest_version"),
                    "max_version": crate.get("max_version"),
                    "updated_at": crate.get("updated_at"),
                    "downloads": crate.get("downloads"),
                }
            )
        except (OSError, KeyError, ValueError, urllib.error.URLError) as error:
            errors.append(f"{name}: {error}")
    write_json(report_path, results)
    return Check(
        "release-activity",
        "maintenance",
        "record current crates.io release activity for every direct registry dependency",
        "blocked" if errors else "pass",
        "some crates.io activity data could not be retrieved" if errors else f"captured current activity for {len(results)} direct dependencies",
        details=errors,
        evidence=[relative(report_path)],
    )


def manual_items(profile: str) -> list[dict[str, Any]]:
    system = "Windows" if profile == "windows" else platform.system()
    if system == "Windows":
        return [
            {
                "id": "windows-scaling",
                "requirement": "Inspect preview at 100%, 150%, and 200% Windows display scaling; export geometry must remain unchanged.",
            },
            {
                "id": "windows-pdf-viewer",
                "requirement": "Open the generated PDF in the target Windows viewer, verify page size, vector appearance, search, selection, and copied μ/Greek/script text.",
            },
            {
                "id": "windows-ui-input",
                "requirement": "Exercise native file dialog and keyboard input on Windows without changing headless export output.",
            },
        ]
    return [
        {
            "id": "macos-retina-preview",
            "requirement": "Inspect the preview on a Retina display and confirm export is independent of window scale.",
        },
        {
            "id": "macos-pdf-viewer",
            "requirement": "Open the generated PDF in Preview/target viewer and verify vectors, clipping, search, selection, and copied semantic text.",
        },
    ]


def check_manual_evidence(
    output_dir: Path, profile: str, supplied: Path | None
) -> list[Check]:
    required = manual_items(profile)
    template_path = output_dir / "manual-evidence.json"
    if supplied is None:
        template = {
            "schema_version": 1,
            "platform": "Windows" if profile == "windows" else platform.system(),
            "reviewer": "",
            "observed_at_utc": "",
            "checks": [
                {**item, "result": "pending", "notes": "", "artifacts": []}
                for item in required
            ],
        }
        write_json(template_path, template)
        return [
            Check(
                item["id"],
                "manual",
                item["requirement"],
                "manual_required",
                "manual inspection evidence has not been supplied",
                evidence=[relative(template_path)],
            )
            for item in required
        ]
    try:
        evidence = json.loads(supplied.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        return [
            Check(
                "manual-evidence-file",
                "manual",
                "manual evidence must be readable structured JSON",
                "fail",
                f"cannot read manual evidence: {error}",
            )
        ]
    by_id = {item.get("id"): item for item in evidence.get("checks", [])}
    reviewer = str(evidence.get("reviewer", "")).strip()
    observed = str(evidence.get("observed_at_utc", "")).strip()
    checks: list[Check] = []
    for required_item in required:
        item = by_id.get(required_item["id"])
        problems: list[str] = []
        if not reviewer:
            problems.append("reviewer is empty")
        if not observed:
            problems.append("observed_at_utc is empty")
        if item is None:
            problems.append("required check is missing")
            result = "missing"
        else:
            result = item.get("result")
            if result not in {"pass", "fail", "blocked"}:
                problems.append("result must be pass, fail, or blocked")
            if not str(item.get("notes", "")).strip():
                problems.append("notes are empty")
        artifact_evidence: list[str] = []
        for artifact in (item or {}).get("artifacts", []):
            path = Path(artifact)
            if not path.is_absolute():
                path = ROOT / path
            if not path.is_file():
                problems.append(f"artifact is missing: {path}")
            else:
                artifact_evidence.append(f"{relative(path)} sha256={sha256(path)}")
        if problems or result == "fail":
            status = "fail"
        elif result == "blocked":
            status = "blocked"
        else:
            status = "pass"
        checks.append(
            Check(
                required_item["id"],
                "manual",
                required_item["requirement"],
                status,
                f"manual result={result} reviewer={reviewer or '<missing>'}",
                details=problems + ([str((item or {}).get("notes", ""))] if item else []),
                evidence=[relative(supplied), *artifact_evidence],
            )
        )
    return checks


def write_reports(output_dir: Path, checks: list[Check], environment: dict[str, Any]) -> int:
    counts = {
        status: sum(check.status == status for check in checks)
        for status in ("pass", "fail", "blocked", "manual_required", "warning")
    }
    result = "fail" if counts["fail"] else (
        "incomplete" if counts["blocked"] or counts["manual_required"] else "pass"
    )
    summary = {
        "schema_version": 1,
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "repository": str(ROOT),
        "result": result,
        "counts": counts,
        "environment": environment,
        "checks": [asdict(check) for check in checks],
    }
    summary_path = output_dir / "summary.json"
    write_json(summary_path, summary)
    problem_checks = [
        check
        for check in checks
        if check.status in {"fail", "blocked", "manual_required", "warning"}
    ]
    lines = [
        f"Part A {environment.get('scope', 'complete')} audit: {result.upper()}",
        f"pass={counts['pass']} fail={counts['fail']} blocked={counts['blocked']} manual={counts['manual_required']} warning={counts['warning']}",
        f"summary={summary_path}",
    ]
    if problem_checks:
        lines.append("")
        lines.append("Problems requiring attention:")
    for check in problem_checks:
        lines.append(f"- [{check.status.upper()}] {check.check_id}: {check.summary}")
        if check.log:
            lines.append(f"  log: {check.log}")
        for detail in check.details[:10]:
            lines.append(f"  {detail}")
    report = "\n".join(lines) + "\n"
    (output_dir / "problem-report.txt").write_text(report, encoding="utf-8")
    print(report, end="")
    return 1 if result == "fail" else (2 if result == "incomplete" else 0)


def main() -> int:
    args = parse_args()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    _, _, git_commit = run(["git", "rev-parse", "HEAD"], ROOT)
    _, _, git_status = run(["git", "status", "--porcelain=v1"], ROOT)
    environment = {
        "platform": platform.platform(),
        "system": platform.system(),
        "machine": platform.machine(),
        "python": platform.python_version(),
        "profile": args.profile,
        "scope": "automated" if args.automated_only else "complete",
        "git_commit": git_commit.strip(),
        "git_status": git_status.strip(),
    }
    checks = [check_platform(args.profile), check_toolchain()]
    checks.append(run_validation(output_dir, args.skip_validation))
    checks.extend((check_font_assets(), check_no_system_font_calls()))
    metadata_checks, packages, metadata_complete = load_metadata(output_dir, args.offline)
    checks.extend(metadata_checks)
    checks.extend(audit_dependency_metadata(output_dir, packages, metadata_complete))
    checks.append(check_advisories(output_dir))
    checks.append(check_release_activity(output_dir, args.offline))
    if not args.automated_only:
        checks.extend(check_manual_evidence(output_dir, args.profile, args.manual_evidence))
    return write_reports(output_dir, checks, environment)


if __name__ == "__main__":
    raise SystemExit(main())
